// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30bg-XopdYZ-3V8i_-o0LXF-V5EQMsn0',
    appId: '1:482960403230:web:b5fedba254fe219fbeb70f',
    messagingSenderId: '482960403230',
    projectId: 'messanger-88aed',
    authDomain: 'messanger-88aed.firebaseapp.com',
    storageBucket: 'messanger-88aed.appspot.com',
    measurementId: 'G-VB958LWH91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCIl4vXlOceoVjc0KVbJJfgLuFd-nnX8',
    appId: '1:482960403230:android:6874ec921aee3463beb70f',
    messagingSenderId: '482960403230',
    projectId: 'messanger-88aed',
    storageBucket: 'messanger-88aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWUyOQryjkgLifW3m_vLC0MsDSF9MJg1o',
    appId: '1:482960403230:ios:8749043d90b3e32ebeb70f',
    messagingSenderId: '482960403230',
    projectId: 'messanger-88aed',
    storageBucket: 'messanger-88aed.appspot.com',
    iosClientId: '482960403230-ve8bs2dj7v6juhll58bq9li08bb8449i.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMessanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWUyOQryjkgLifW3m_vLC0MsDSF9MJg1o',
    appId: '1:482960403230:ios:8749043d90b3e32ebeb70f',
    messagingSenderId: '482960403230',
    projectId: 'messanger-88aed',
    storageBucket: 'messanger-88aed.appspot.com',
    iosClientId: '482960403230-ve8bs2dj7v6juhll58bq9li08bb8449i.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMessanger',
  );
}
